config {
    type: "assertion",
    tags: ["qa"]
}

WITH
  MismatchRows AS (
  SELECT
    *
  FROM (
    SELECT
      DISTINCT sa.PrimaryKey AS saPrimaryKey,
      sa.OrderID AS saOrderID,
      pd.PrimaryKey AS pdPrimaryKey,
      pd.OrderID AS pdOrderID
    FROM
      ${ref("sales_orders_silver")} sa
    LEFT JOIN
      `xfuze-mattel-uat.xfuze_sales_order.sales_orders_silver` pd
    ON
      sa.PrimaryKey = pd.PrimaryKey
      AND sa.OrderID = pd.OrderID)
  WHERE
    pdOrderID IS NULL)
SELECT
  COUNT(*) AS cnt
FROM
  MismatchRows
HAVING
  cnt > 0
