-- config { type: "assertion", tags: ["qa"] }

-- WITH MismatchRows AS (
-- SELECT * FROM (
-- SELECT DISTINCT
-- sa.ProductCode as saProductCode
-- , sa.SKUCode as saSKUCode
-- , pd.ProductCode as pdProductCode
-- , pd.SKUCode as pdSKUCode
-- FROM ${ref("stock_allocation_feeder_filtered")} sa
-- LEFT JOIN `bi-mossbros-uat.sdv_product.sdv_product_variant_details` pd
-- ON sa.ProductCode = pd.ProductCode
-- AND sa.SKUCode = pd.SKUCode)
-- WHERE pdSKUCode IS NULL)



-- SELECT count(*) AS cnt
-- FROM MismatchRows
-- HAVING cnt > 0