config {
    tags: ["products", "daily"],
    schema: "xt_gsheets",
  description: "Products data from Mattel gsheet",
  disabled: true,
  type: "table",
columns: {

  }
}

--- DUE TO PERMISSIONS ISSUES THIS IS RUNNING AS A SCHEDULED QUERY FOR NOW

WITH
 BASE_DATA_2026 AS (
        SELECT
            *
        FROM
            ${ref("xt_products_2026_gs")}
    )



SELECT
ARRAY_AGG(e LIMIT 1)[OFFSET(0)].*
FROM BASE_DATA_2026 e
GROUP BY e.Sku


